<?php
// use Drupal\Core\Form\FormStateInterface;

// function questionnaire_lists_form_alter(&$form,$form_state, $form_id) {
//   if ($form_id == 'anketa_k_dkr') {
//       $form['actions']['submit']['#validate'][] = 'questionnaire_lists_operation_form_validate';
//   }
// }

// function questionnaire_lists_operation_form_validate(&$form, $form_state, $form_id) {
//   // $form_state->setValue('team_id_timlida', '19');
//   $values = ['team_id_timlida' => '19'];
//   $form_state->setValues($values);
// }

function questionnaire_lists_theme($existing, $type, $theme, $path) {
  return [
    'questionnaires-employee-display' => [
      'variables' => [
        'test_var' => NULL,
        'submissions' => NULL,
          'user' => NULL,
    ],
      'template' => 'questionnaires-employee',
    ],
  ];
}
