<?php

function questionnaire_lists_theme($existing, $type, $theme, $path) {
    return [
        'questionnaires-employee-display' => [
            'variables' => [
                'teamlead' => NULL,
                'submissions' => NULL,
            ],
            'template' => 'questionnaires-employee',
        ],
        'questionnaires-teamlead-display' => [
            'variables' => [
                'submissions' => NULL,
            ],
            'template' => 'questionnaires-teamlead',
        ],
    ];
}
