<?php
use Drupal\Core\Form\FormStateInterface;
// use Drupal\user\Entity\User;



function questionnaire_hooks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // kint($form_id);
  // if ($form_id == 'webform_submission_filter_form') {
  //   // kint($form_state);
  //     $form['actions']['submit']['#validate'][] = 'questionnaire_hooks_form_validate';
  // }
      // if ($form_id == 'webform_submission_filter_form') {
        // $form['actions']['#submit'][] = 'questionnaire_hooks_form_validate';
      // }
      if ($form_id == 'webform_submission_anketa_k_dkr_add_form') {
        foreach (array_keys($form['actions']) as $action) {
          if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
            $form['actions'][$action]['#validate'][] = 'questionnaire_hooks_form_validate';
            drupal_set_message($form_id);
          }
        }
      }
}

function questionnaire_hooks_form_validate(&$form, FormStateInterface $form_state) {
  $user_roles = \Drupal::currentUser()->getRoles();
  drupal_set_message('user roles is: ' . print_r($user_roles));

  $form_state->setValue('id_timlida', '19');
  \Drupal::logger(' id_timlida')->notice('id_timlida 19 submit ');

  // $values = ['team_id_timlida' => '19'];
  // $form_state->setValues($values);
}

